### ISSUE TITLE
AGChv14 not working

### ISSUE THREAD

**Issue by GabrielaLopez** [GabrielaLopez/BiomasaFP#13]
Submitted by Fernanda
Please check if AGChv14 works well for these set of plots in this current version of the package? In the earlier version of the package is working well, so for my use now it is perfectly fine, but if I use the new version that was available yesterday it seems there is a bug in that.

**Comment by martinsulli** [comment]
Can you send me the list of plots where AGBChv14 fails? Does it give an error or inappropriate values?

**Comment by GabrielaLopez** [comment]
Martin, I checked this  issue using the data sent by Fernanda , looking at the code in more detail and it seems you already solved this issue.  I also checked the output against a new Biomas query: AGB Chave 2014.
